/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.de.verificação.de.voos.Telas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.de.verificação.de.voos.Entidades.Aviao;
import projeto.de.verificação.de.voos.Entidades.Voo;
import projeto.de.verificação.de.voos.Persistencia.Arquivo.AviaoDAOImplArq;
import projeto.de.verificação.de.voos.Persistencia.Arquivo.VooDAOImplArq;
import projeto.de.verificação.de.voos.Persistencia.AviaoDAO;
import projeto.de.verificação.de.voos.Persistencia.VooDAO;

/**Tela para Criação, Edição e Exclusão de Objetos da Classe Aviões
 *
 * @author Victor Hugo Duarte
 */
public class JPanelAviao extends javax.swing.JPanel {
    private VooDAO voo_banco = new VooDAOImplArq();
    private AviaoDAO aviao_banco = new AviaoDAOImplArq();
    private int id=0; //Usado pelo método editar
    /**
     * Creates new form JPanelAviao
     */
    public JPanelAviao() {
        initComponents();
        carregarTabela();
    }

    /**Método que carrega a tabela de Cidades
     *
     * 
     */
    private void carregarTabela(){
        List<Aviao> lista = aviao_banco.lista_do_banco();
        DefaultTableModel modeloTabela = (DefaultTableModel) jTable.getModel();
        int qntLinhas = modeloTabela.getRowCount();
        
        
        for (int i = 0; i < qntLinhas; i++) {
            modeloTabela.removeRow(0);
        }
        for (int i=0;i<lista.size();i++){
            Aviao aviao = lista.get(i);
            Object[] linha = new Object[3];
            linha[0] = aviao.getId();
            linha[1] = aviao.getNome();
            modeloTabela.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelAvioes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonSalvar1 = new javax.swing.JButton();

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Editar");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelAvioes.setText("Aviões");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButtonSalvar)
                                .addGap(49, 49, 49)
                                .addComponent(jButtonEdit)
                                .addGap(47, 47, 47)
                                .addComponent(jButtonExcluir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabelAvioes)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jButtonSalvar1))
                .addGap(21, 21, 21)
                .addComponent(jLabelAvioes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    /**Cria um objeto da Classe Aviões.Se ele já existir no banco, será realizado uma edição. Senão, um salvamento.
     *
     * @param evt
     */
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Aviao a = new Aviao();

        a.setNome(jTextFieldNome.getText());
        if (!"".equals(a.getNome())){
            if(id!=0){
                a.setId(id);
                id=0;
                aviao_banco.editar(a);
            } else {
                aviao_banco.salvar(a);
            }
        }
        jTextFieldNome.setText("");
        carregarTabela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**Transfere para o jtextFieldName o nome armazenado no banco e altera a variavel id para que o método de salvamento possa ser realizado de maneira correta
     *
     * @param evt
     */
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        int linha= jTable.getSelectedRow();
        if (linha!=-1){
            int id =(int) jTable.getValueAt(linha, 0);
            jTextFieldNome.setText(""+aviao_banco.procurar_por_id(id).getNome());
            this.id=id;
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**Exclui um determinado elemento do Banco de dados com base em qual elemento está selecionado na tabela de Aviões
     *
     * @param evt
     */
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int[] linha = jTable.getSelectedRows();
        ArrayList<Voo> v = voo_banco.lista_do_banco();
        boolean alerta=false;
        //System.out.println(Arrays.toString(linha));
        for (int pos: linha) {
            boolean existe=false;
            int id = (int) jTable.getValueAt(pos, 0);
            for (Voo v1 : v) {
                if(v1.getAviao().getId()==id){
                    existe=true;
                    break;
                }
            }
            if(!existe){
                aviao_banco.excluir(id);
            } else{
                alerta=true;
            }
        }
        if(alerta){
            JOptionPane.showMessageDialog(null, "Não foi possivel excluir algum avião, delete o voo associado a ele antes!", "Atenção!", JOptionPane.ERROR_MESSAGE);

        }
        carregarTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**Copia do método do Botão Salvar, foi criado para permitir a flexibilidade de poder se escolher qual botão apertar. Assim como o outro, cria um objeto da Classe Aviao.Se ele já existir no banco, será realizado uma edição. Senão, um salvamento.
     *
     * @param evt
     */
    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        Aviao a = new Aviao();

        a.setNome(jTextFieldNome.getText());
        if (!"".equals(a.getNome())){
            if(id!=0){
                a.setId(id);
                id=0;
                aviao_banco.editar(a);
            } else {
                aviao_banco.salvar(a);
            }
        }
        jTextFieldNome.setText("");
        carregarTabela();
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JLabel jLabelAvioes;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
